export const ITEM_ORDER_BEGIN = "ITEM_ORDER_BEGIN";
export const ITEM_ORDER_SUCCESS = "ITEM_ORDER_SUCCESS";
export const ITEM_ORDER_FAILURE = "ITEM_ORDER_FAILURE";

export const GET_ITEMS_BEGIN = "GET_ITEMS_BEGIN";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";

export const GET_CART_BEGIN = "GET_CART_BEGIN";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const DELETE_CARTITEM_BEGIN = "DELETE_CARTITEM_BEGIN";
export const DELETE_CARTITEM_SUCCESS = "DELETE_CARTITEM_SUCCESS";
export const DELETE_CARTITEM_FAILURE = "DELETE_CARTITEM_FAILURE";

export const UPDATE_CARTITEM_BEGIN = "UPDATE_CARTITEM_BEGIN";
export const UPDATE_CARTITEM_SUCCESS = "UPDATE_CARTITEM_SUCCESS";
export const UPDATE_CARTITEM_FAILURE = "UPDATE_CARTITEM_FAILURE";
